# Generated by Django 4.1.2 on 2023-02-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_receipient_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='reated',
            new_name='created',
        ),
    ]
